using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle RegionMurlocSpawn { get; set; } = new Rectangle(-9824f, -6336f, -7488f, -5024f);
	public static Rectangle RegionUndeadSpawn { get; set; } = new Rectangle(-1600f, -7616f, 320f, -5216f);
	public static Rectangle HeroSpawn { get; set; } = new Rectangle(-896f, -736f, 96f, 224f);
	public static Rectangle RegionUndeadSpawnZombieMore { get; set; } = new Rectangle(5920f, 5088f, 8000f, 7296f);
	public static Rectangle RegionUndeadSpawnDemons { get; set; } = new Rectangle(-5792f, 4832f, -4096f, 7232f);
	public static Rectangle NoViolanceArea { get; set; } = new Rectangle(-2528f, -2400f, 1760f, 1856f);

}